version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/testDB
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev  # Use 'start:prod' for production

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
